name: marimo_client
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  flutter_screenutil: ^5.9.3
  flutter_cube: ^0.1.1
  model_viewer_plus: ^1.9.1
  webview_flutter: ^4.10.0
  flutter_blue_plus: ^1.35.3
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Freesentation
      fonts:
        - asset: assets/fonts/Freesentation-1Thin.ttf
          weight: 100
        - asset: assets/fonts/Freesentation-2ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Freesentation-3Light.ttf
          weight: 300
        - asset: assets/fonts/Freesentation-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Freesentation-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Freesentation-6SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Freesentation-7Bold.ttf
          weight: 700
        - asset: assets/fonts/Freesentation-8ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Freesentation-9Black.ttf
          weight: 900

  assets:
    - assets/images/
    - assets/images/cars/
    - assets/images/logo/
    - assets/models/uber_car.obj
    - assets/models/uber_car.mtl
    - assets/models/uberBlack.dae.glb
    - assets/models/generic_sedan.glb
    - assets/models/uberXL.glb
